# platform :ios, '7.0'
# use_frameworks!

target 'TuyaSmartKit_Example' do
    pod 'MBProgressHUD'
    pod 'BlocksKit'
    
    pod 'TuyaSmartKit', :path => '../'

    target 'TuyaSmartKit_Tests' do
        inherit! :search_paths
    end
    
end
