# platform :ios, '7.0'
# use_frameworks!

target 'TuyaSmartKitDemo' do
    pod 'MBProgressHUD', '~> 0.9.2'
    pod 'BlocksKit'
    pod 'SDWebImage'
    pod 'DACircularProgress'
    
    pod 'TuyaSmartKit', :path => '../'
    
end
