# platform :ios, ‘8.0’

target 'TuyaSmartKitDemo' do
    pod 'MBProgressHUD', '~> 0.9.2'
    pod 'BlocksKit'
    pod 'SDWebImage'
    pod 'DACircularProgress'
    pod 'CocoaLumberjack'
    
    pod 'TuyaSmartKit', :path => '../'
    
end
